- name: Install Necessary Software
  hosts: all
  user: ec2-user
  become: true
  roles:
  -  role: hadoop-config

- name: Setup Master Node
  hosts: master
  user: ec2-user
  become: true
  roles:
  - role: master-setup

- name: Setup Slave  Node
  hosts: slave
  user: ec2-user
  become: true
  roles:
  - role: slave-setup

